layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
#     - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: IAmSuyogJadhav
  linkedin: IAmSuyogJadhav
#   medium: @IAmSuyogJadhav
  # stackoverflow: your_user_id
  telegram: IAmSuyogJadhav
  twitter: IAmSuyogJadhav
  youtube: IAmSuyogJadhav
  # vk: your_username

topics:
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png
    
  - name: TensorFlow
    web_url: https://github.com/topics/tensorflow
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/tensorflow/tensorflow.png
  
  - name: OpenCV
    web_url: https://github.com/topics/opencv
    image_url: https://raw.githubusercontent.com/github/explore/433c866c69205a7a46dc73d8b4bbc7c12a6638f6/topics/opencv/opencv.png

  - name: Flask
    web_url: https://github.com/topics/flask
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/flask/flask.png
  
  - name: Numpy
    web_url: https://github.com/topics/Numpy

  - name: Pandas
    web_url: https://github.com/topics/pandas

  - name: OpenCV
    web_url: https://github.com/topics/pytorch

